<a href="https://colab.research.google.com/github/nqtien12/AI/blob/main/ANN_Week8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron

x=[[0,0],[0,1],[1,0],[1,1]]
t=[0,1,1,1]
model=Perceptron()
model.fit(x,t)
model.score(x,t)


1.0

In [ ]:
X1=[[0.5,-1],[0.5,0.5],[-10,1],[0.6,0]]
Y1=model.predict(x)
print(Y1)
model.score(X1,Y1)


[0 1 1 1]


0.75

In [ ]:
x1=[[0.5,0.5],[0.5,-0.5],[0.3,-0.5],[-0.1,-1]]
y=[1,1,0,0]
model=Perceptron()
model.fit(x1,y)
model.score(x1,y)


1.0

In [ ]:
z=[[0.9,0.2],[0.3,-0.1],[0.1,-0.5],[-0.4,-0.9]]
Y1=model.predict(x1)
print(Y1)
model.score(z,Y1)

[1 1 0 0]


1.0

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler


In [ ]:
iris = datasets.load_iris()
print(iris) 

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [36]:
from sklearn.base import TransformerMixin
from pandas.core.arrays.interval import ScalarIndexer
X=iris.data
y=iris.target
print(X[:5])
print(y[:5])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size = 0.3)
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)
X_test_std=sc.transform(X_test)
print(X_train_std[:5])




[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[-0.48627258 -1.41699414 -0.1049965  -0.33518064]
 [ 2.10792988 -0.97745386  1.71349952  1.38482529]
 [ 0.57499206  0.12139684  0.91790751  0.72328454]
 [ 0.45707377 -0.53791358  0.69059551  0.3263601 ]
 [-0.95794576  0.78070726 -1.3552125  -1.39364583]]


In [41]:
model=Perceptron(max_iter=40,eta0=0.1,random_state=0) 
model.fit(X_train_std,y_train)
y_predict=model.predict(X_test_std)
print(y_predict)
print(y_test)
print('Do chinh xac cua mo hinh',accuracy_score(y_test,y_predict))

[0 2 2 2 0 0 2 0 0 2 2 0 0 0 0 2 2 0 1 2 0 0 2 2 1 2 0 2 0 0 2 2 0 0 0 0 2
 2 0 2 2 2 0 0 2]
[0 1 2 2 0 0 2 1 1 2 1 0 0 0 1 1 1 0 1 2 0 0 1 2 1 1 0 2 0 0 2 2 0 0 1 0 2
 1 0 2 2 1 0 0 1]
Do chinh xac cua mo hinh 0.7111111111111111


In [53]:
import numpy as np
import pandas as pd
url='crabs.csv'
data = pd.read_csv(url)
data.head(20)





speies sex  index  fontallip  rearwidth  length  width  depth
0       B   M      1        8.1        6.7    16.1   19.0    7.0
1       B   M      2        8.8        7.7    18.1   20.8    7.4
2       B   M      3        9.2        7.8    19.0   22.4    7.7
3       B   M      4        9.6        7.9    20.1   23.1    8.2
4       B   M      5        9.8        8.0    20.3   23.0    8.2
5       B   M      6       10.8        9.0    23.0   26.5    9.8
6       B   M      7       11.1        9.9    23.8   27.1    9.8
7       B   M      8       11.6        9.1    24.5   28.4   10.4
8       B   M      9       11.8        9.6    24.2   27.8    9.7
9       B   M     10       11.8       10.5    25.2   29.3   10.3
10      B   M     11       12.2       10.8    27.3   31.6   10.9
11      B   M     12       12.3       11.0    26.8   31.5   11.4
12      B   M     13       12.6       10.0    27.7   31.7   11.4
13      B   M     14       12.8       10.2    27.2   31.8   10.9
14      B   M     15       12.8       10.9    27.4   31.5   11.0
15      B   M     16       12.9       11.0    26.8   30.9   11.4
16      B   M     17       13.1       10.6    28.2   32.3   11.0
17      B   M     18       13.1       10.9    28.3   32.4   11.2
18      B   M     19       13.3       11.1    27.8   32.3   11.3
19      B   M     20       13.9       11.1    29.2   33.3   12.1

In [52]:
import pandas as pd
url= 'crabs.csv'
df= pd.read_csv(url)
data=df.loc[df['speies']== 'B']
data.loc[df['sex']=='F'] = '0'
data.loc[df['sex']=='M'] = '1'
print(data)


   speies sex index fontallip rearwidth length width depth
0       1   1     1         1         1      1     1     1
1       1   1     1         1         1      1     1     1
2       1   1     1         1         1      1     1     1
3       1   1     1         1         1      1     1     1
4       1   1     1         1         1      1     1     1
..    ...  ..   ...       ...       ...    ...   ...   ...
95      0   0     0         0         0      0     0     0
96      0   0     0         0         0      0     0     0
97      0   0     0         0         0      0     0     0
98      0   0     0         0         0      0     0     0
99      0   0     0         0         0      0     0     0

[100 rows x 8 columns]


<ipython-input-52-248f82c0d336>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[df['sex']=='F'] = '0'


In [54]:
data = pd.read_csv('crabs.csv')
print(data.head())
print(data.shape)

data.drop(data.index[100:200],axis=0, inplace=True)
data.shape

data.replace(to_replace="M",value=0, inplace=True)
data.replace(to_replace="F",value=1, inplace=True)
data.head()

data.drop(data.columns[[0,2]], axis=1, inplace=True)
data.head()

X = data[['fontallip', 'rearwidth', 'length', 'width', 'depth']].to_numpy()
y = data['sex'].to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

model = Perceptron(max_iter=40, eta0=0.1, random_state=0) #max_iter: số lần học, eta0: tốc độ học (càng lớn, sai số càng nhiều)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print("Do chinh xac cua mo hinh: ", accuracy_score(y_test,y_pred))

  speies sex  index  fontallip  rearwidth  length  width  depth
0      B   M      1        8.1        6.7    16.1   19.0    7.0
1      B   M      2        8.8        7.7    18.1   20.8    7.4
2      B   M      3        9.2        7.8    19.0   22.4    7.7
3      B   M      4        9.6        7.9    20.1   23.1    8.2
4      B   M      5        9.8        8.0    20.3   23.0    8.2
(200, 8)
[0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0]
Do chinh xac cua mo hinh:  0.8
